import './globals.css';
import type { Metadata } from 'next';
import Script from 'next/script';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <title>{process.env.NEXT_PUBLIC_TITLE}</title>
            <head>
                {/* 网页描述 */}
                <meta name='description' content="chovrio'blog" />
                {/* 网页关键词 */}
                <meta
                    name='keywords'
                    content="chovrio blog chovrio'blog next博客"
                />
                {/* 移动端适配 */}
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1.0'
                />
                {/* 网站的icon图标 */}
                <link rel='icon' href='/favicon.ico' />
                <Script src='/live2d/L2Dwidget.min.js'></Script>
                <Script src="/live2d/index.js"></Script>
            </head>
            <body>{children}</body>
        </html>
    );
}
